name: test-workflow
on: 
    push:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: print directory
              run: pwd
            - name: list file
              run: ls


